Use clipboardy
goessner/mdmath pull request #17
Opened 2017-04-30 06:57 UTC by floatdrop

Closes #13

2017-05-12 02:19 UTC, TonySFU commented
I tried this version, but still has the same issue, sorry.

2017-05-12 14:16 UTC, TonySFU requested changes
add this code on the top of extension.js file will solve this problem.

process.env["LC_CTYPE"] = process.env.LC_CTYPE || "UTF-8";

2017-05-12 14:35 UTC, floatdrop commented
We will add it in https://github.com/sindresorhus/clipboardy/issues/15#issuecomment-301092218  - looks like it should be there.

2017-05-13 09:58 UTC, floatdrop commented
@TonySFU this is fixed in `clipboardy@1.1.2`.

2017-05-13 10:53 UTC, sindresorhus commented on package.json
> +        "clipboardy": "^1.1.1",
Bump it to 1.1.2, just to make sure it's never deduped to a lower version.

2017-05-14 17:12 UTC, goessner commented
Thanks a lot for your help. I reused your modifications with some other bug fixes directly in the source.

2017-05-14 17:12 UTC, closed without merging

2017-05-14 19:24 UTC, TonySFU commented
Did you test on windows platform? Clip function seems not working on newest version mdmath.

2017-05-14 19:34 UTC, floatdrop commented
@TonySFU we have [tests](https://ci.appveyor.com/project/sindresorhus/clipboardy/branch/master) on Windows platform.

2017-05-14 19:42 UTC, TonySFU commented
That's weird, the Clip Markdown+Math to HTML function not return any result on my windows 10 pc. Works great on the macbook.

2017-05-15 06:31 UTC, goessner commented
Hmm ... I did test it on windows 10 .. it worked.

Now I have tested it again .. and even included your snippet

# 一级标题
* HI
* HIHI
## 二级标题
### 三级标题

this also works (copying from clipboard to html document).

I will now delete my mdmath extension and reinstall it again from marketplace.

2017-05-15 07:50 UTC, goessner commented
I obviously forgot some entries in the (flat) `dependencies` list in `package.json`.

Hopefully this was it ?! (1.2.9)

2017-05-15 16:46 UTC, TonySFU commented
I found this problem only happen when markdown file is large.
https://github.com/goessner/mdmath/issues/19

2017-05-24 17:12 UTC, goessner commented
@sindresorhus, @TonySFU: Isn't new [copy-text-to-clipboard](https://github.com/sindresorhus/copy-text-to-clipboard) a better alternative to `clipboardy` now ?

2017-05-24 21:13 UTC, TonySFU commented
it related on clipboardy, and this one just work in browsers. For now it works great on macOS. When markdown file is large, clipboardy will hit limit on arguments length in Windows. @floatdrop try to fix it https://github.com/goessner/mdmath/issues/19